apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: html-content
    options:
      immutable: true
    files:
      - html/index.html

secretGenerator:
  - name: demo-secret
    literals:
      - password=changeme
